/* Generated By:JavaCC: Do not edit this line. GbkPropParserConstants.java */
package org.raygoza.bx.parsers;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GbkPropParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 1;
  /** RegularExpression Id. */
  int SLASHX = 7;
  /** RegularExpression Id. */
  int EQUAL = 8;
  /** RegularExpression Id. */
  int FEATURE_TYPE = 14;
  /** RegularExpression Id. */
  int WD = 15;
  /** RegularExpression Id. */
  int STRING_LITERAL = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int PINTERVAL = 18;
  /** RegularExpression Id. */
  int NINTERVAL = 19;
  /** RegularExpression Id. */
  int OINTERVAL = 20;
  /** RegularExpression Id. */
  int RANGEOP = 21;
  /** RegularExpression Id. */
  int ORIGINS = 22;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INTERVAL = 1;
  /** Lexical state. */
  int LIT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMBER>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\" /\"",
    "\"=\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<FEATURE_TYPE>",
    "<WD>",
    "<STRING_LITERAL>",
    "\",\"",
    "<PINTERVAL>",
    "<NINTERVAL>",
    "<OINTERVAL>",
    "\"..\"",
    "\"ORIGIN\"",
  };

}
